### PR TITLE
Add Korean translation

### PR DESCRIPTION
**Pull request by green1052**

### CODE REVIEW

**Review by yujincheng08 — CHANGES_REQUESTED** [review]
you need to add ko to app/build.gradle to enable ur translation

**Comment by green1052** [comment]
Is it https://github.com/green1052/LSPosed/blob/master/app/build.gradle#L40?

**Comment by yujincheng08** [comment]
yes

**Comment by green1052** [comment]
I've added it.

**Review by yujincheng08 — APPROVED** [review]
great now

**Comment by green1052** [comment]
Thank you.

**Pull request merged**
