### PR TITLE
More MD3 designs

### PR DESCRIPTION
**Pull request by yujincheng08**

### CODE REVIEW

**Comment by canyie** [comment]
Really wanna to close this immediately

**Review by canyie — CHANGES_REQUESTED** [review]
Most users don't like the new md3 design. Request changes to block merging.
IMG_20220122_104158_787

**Review by canyie — APPROVED** [review]
SO UGLY THE NEW DESIGN IS!
GOOD BYE RIKKA DESIGN! LONG LIVE THE RIKKA DESIGN!! FOREVER!!

**Comment by mywalkb** [comment]
> SO UGLY THE NEW DESIGN IS! 

maybe it will be useful to complete #9 😀

**Comment by mywalkb** [comment]
> SO UGLY THE NEW DESIGN IS! 

a project which works in background design is useless! I used the app about 5 minutes in one year.

**Pull request merged**
