### PR TITLE
Support CLI

### LINKED ISSUE #405: [TODO] CLI - Command Line Interface
**Detail**:
First, thank you very much for the entire LSPosed team and community.
 
Xposed is a reality in our lives that we absolutely will not live without more.

I love EdXposed.
I like LSPosed. But I'm sure I will love it too.

Undoubtedly, we all preferred that both projects continued being developed together.
The desire, pleasure, commitment and dedication of the LSPosed team is really admirable.

The primary difference between LSPosed and EdXposed is that LSPosed works exclusively through scopes.
Like MagiskHide, LSPosed needs you to enable or disable scopes for each app.

But, we may want to enable the scopes in a massive way.

With MagiskHide, we can use the command line interface (CLI) to enable and disable apps.

With LSPosed, it would be really very helpful to use a CLI (Command Line Interface).
If a CLI (Command Line Interface) were implemented, certainly I would migrate totally to LSPosed.

I wrote a perl script, it makes all the service for me for long years.
It does:
- (Deprecated) Add apps to automatic hibernation (Greenify).
- (Deprecated) Add apps to hide root (Rootcloak2).
- (Deprecated) Add patterns to hide root (Rootcloak2).
- Add apps to hide root (MagiskHide).
- Check all global settings (XPrivacyLua).
- Enable notification for all apps (XPrivacylua).
- Enable previously selected hooks for the previously selected apps (XPrivacyLua).
- Add scopes to the modules, following the same apps enabled in xprivacylua (LSPosed).
- Enable previously selected modules (LSPosed).
- Check if any app was enabled by mistake in any of the previous steps.

This guarantees with 100% precision that everything will always be perfectly configured, following my own filters, helping me to save my time and preventing me to do something mistakenly due to the exhaustive sequence of steps.

The question here is, I need to use the SQLite to apply the changes in the LSPosed database, which is a very unfortunately not recommended practice.

So, it would be of extreme importance the possibility of enabling and disabling the modules and the scopes through a command line interface (CLI), like:

`lsposed enable module.pkg.name`
`lsposed disable module.pkg.name`

`lsposed add module.pkg.name app.pkg.name`
`lsposed rm module.pkg.name app.pkg.name`

### PR DESCRIPTION
**Pull request by yearsyan**
Close #405 
Please use `/data/adb/lspd/bin/lsposed usage` to get detail usage. 
Support both riru and zygisk inject mode.

### CODE REVIEW

**Comment by yujincheng08** [comment]
Many thanks for your implementation.
I have some suggestions:
1. use `daemon.apk` instead of `lspd.dex`
2. Use `jcommander`

**Comment by yujincheng08** [comment]
Further, I think it would be better to add a compile-time UUID for authorization.

**Comment by yearsyan** [comment]
Thanks for you suggestion. I will continue to contribute code to the project.

**Comment by vvb2060** [comment]
鉴于用户几乎不可能拒绝xposed模块的root请求，cli使模块可直接操作作用域，导致作用域功能失去意义。甚至能够做到监控用户打开lsposed app，及时去除异常作用域范围。
鉴于此，我认为需要有一个合理的解决方案，在最坏的情况下，放弃cli功能。

**Comment by vvb2060** [comment]
操作LSPosed储存配置信息的数据库需要重启后才能生效；或者重启lspd daemon，而这会导致app显示警告。

**Comment by yearsyan** [comment]
> 操作LSPosed储存配置信息的数据库需要重启后才能生效；或者重启lspd daemon，而这会导致app显示警告。
> 
> 事实上，我们已经发现有人直接操作数据库，但这会导致lsposed app显示警告，所以没有被模块普及使用。

最坏的情况下，恶意的root程序可以通过ptrace修改Manager。在root权限下的恶意应用与反恶意应用攻防都会演变成猫鼠游戏。对于CLI的安全，我最合理的保护应该是类似于ADB的弹窗授权。

**Comment by canyie** [comment]
拥有 root 权限之后甚至可以直接替换掉 lspd 然后阻止警告显示。我不认为对已经拥有 root 的应用设防有任何意义和可行性。

**Comment by vvb2060** [comment]
攻防首先考虑成本问题，需要提升恶意行为的成本。目前的实现极大方便了恶意行为而没有任何防御措施。

**Comment by yearsyan** [comment]
是的，我们需要严谨的讨论如何保护CLI：
1. 是否需要默认开启CLI功能
2. 通过何种方法来保护CLI功能不被滥用

**Comment by mywalkb** [comment]
For protection, can a magisk-like mechanism be implemented? with PID and PPID it should be possible to trace back to the module that call the cli. There is just a problem with uid associated to multiple packages.

**Comment by yearsyan** [comment]
> For protection, can a magisk-like mechanism be implemented? with PID and PPID it should be possible to trace back to the module that call the cli. There is just a problem with uid associated to multiple packages.

As far as I know, trace caller is impossible. Due to selinux, setuid is disabled so magisk provided a socket to run command as root and all root command will be executed by magisk daemon. If we trace caller by parent pid, finally we will get the magisk deamon process instead of the real caller.

**Comment by mywalkb** [comment]
> As far as I know, caller tracing is impossible

right the parent is always magiskd. Sorry my fault.

**Comment by mywalkb** [comment]
Oh noooh, closed without merge why?
It seemed like an interesting feature, do not lose hope I think that sooner or later @yujincheng08 will merge.
After this PR the next step was module api #9

**Comment by waysup** [comment]
This is exactly what I've been expecting, should have been merged.

**Comment by mywalkb** [comment]
@waysup you can find the patch in my mod mywalkb/LSPosed_mod. 
I don't think they will implement/merge it.
In the last month the developing is stopped and the cli is not developed.

**Comment by sshock** [comment]
I don't understand why this was closed.  CLI support is so important for some of us.

**Comment by pkilller** [comment]
> 

Hope this helps: https://github.com/pkilller/LSPosed-with-CLI

**Comment by sshock** [comment]
> Hope this helps: https://github.com/pkilller/LSPosed-with-CLI

Thanks @pkilller .  I appreciate it.  However, I should have mentioned that I already went ahead with @mywalkb 's fork here: https://github.com/mywalkb/LSPosed_mod

**Pull request closed without merging**
