### PR TITLE
Make provision to de-activate LogWatchDog

### PR DESCRIPTION
**Pull request by msvamp**

### CODE REVIEW

**Comment by msvamp** [comment]
> In which situation is this needed?

I think LSPosed should not forcefully enable logging for Android, so I am making it configurable (keeping enabled by default to not change current behaviour).
There are some apps which refuse to work when logging is enabled or developer options are enabled, so this is useful in such cases.

**Comment by aviraxp** [comment]
> > In which situation is this needed?
> 
> I think LSPosed should not forcefully enable logging for Android, so I am making it configurable (keeping enabled by default to not change current behaviour).
> There are some apps which refuse to work when logging is enabled or developer options are enabled, so this is useful in such cases.

Not sure how logging is related to the cases you mentioned. Logging is a standard behavior of android.

**Comment by msvamp** [comment]
> Not sure how logging is related to the cases you mentioned. Logging is a standard behavior of android.

@aviraxp Some apps refuse to start when `persist.log.tag` property value is not equal to `Settings` (Mainly happens with some banking and finance apps)
With this change, the app is working fine if I turn off Logger buffer size and developer options.

@Howard20181 why close this so soon? We can discuss other ways if you don't like this 🥺

**Comment by aviraxp** [comment]
I don't like yhe approach but i will keep it open for further discussion. Can you elaborate technical details on those apps?

**Comment by msvamp** [comment]
> I don't like yhe approach but i will keep it open for further discussion. Can you elaborate technical details on those apps?

@aviraxp Thank you. Basically there are many local banking apps which do not like developers. They do not start, or disable certain functionality if developer options are enabled or if some default Android settings are changed. I don't know how they read the values of settings, I can try to decompile them and check. Do you have any other ideas to spoof the values of settings to such apps?

**Comment by Howard20181** [comment]
> When `persist.log.tag` property value is not equal to `Settings` 

Why does this happen and why stop `logd` can bypass?

**Comment by Howard20181** [comment]
Which bank app?

**Comment by vvb2060** [comment]
> Some apps refuse to start when persist.log.tag property value is not equal to Settings (Mainly happens with some banking and finance apps)

If there is an app that requires disable logs before opening it, you should uninstall LSPosed.

**Comment by msvamp** [comment]
> Which bank app?

@Howard20181 It's a popular bank in my country. I do not want to disclose the name for privacy reasons. I can try to use dex2smali and find the exact code that it uses to check for device changes, but need some time for this.

> If there is an app that requires disable logs before opening it, you should uninstall LSPosed.

@vvb2060 But why not give user the option to choose whether logging should be enabled or not? Why stop using LSPosed? I will either have to fork and use it with the code change, or find a module that can hide this property for the app 😞

**Comment by vvb2060** [comment]
Because I don't believe there is an app that can't be opened on any Android device, unless log is disabled.

**Comment by msvamp** [comment]
> Because I don't believe there is an app that can't be opened on any Android device, unless log is disabled.

I know for sure that when you run `getprop` in a terminal on an unmodified Android device without touching its bootloader, without rooting, and without enabling developer options - then there are no properties starting with `persist.log` or `persist.logd` on the device. LSPosed creates them in the first place and then the app in question, stops working.
I made this PR only to make a provision to prevent LSPosed from touching these properties.

**Comment by HandsomeXi** [comment]
This commit works great for me, frequent logging causes performance degradation on the device.

**Pull request closed without merging**
