### PR TITLE
[core] Check variant_path when updating config file

### LINKED ISSUE #88: [FR?] Add "reboot required" warning after switching variant

### PR DESCRIPTION
**Pull request by kotori2**
Close #88

### CODE REVIEW

**Review by yujincheng08 — CHANGES_REQUESTED** [review]
macro 坏！用 inline static function 呀

**Comment by kotori2** [comment]
> macro 坏！用 inline static function 呀

首先inline并不能保证inline，其次我觉得就一行字的事用函数简直在浪费时间（

**Comment by yujincheng08** [comment]
ALWAYSINLINE

**Review by yujincheng08 — APPROVED** [review]
给 ksm 倒一杯卡布奇诺

**Comment by kotori2** [comment]
https://clang.llvm.org/docs/AttributeReference.html#always-inline-force-inline

> Does not guarantee that inline substitution actually occurs.

**Pull request merged**
