### PR TITLE
Adding French translation

### PR DESCRIPTION
**Pull request by xerta555**
Ready to be merged into master branch.
Nice work!

### CODE REVIEW

**Comment by aviraxp** [comment]
https://github.com/LSPosed/LSPosed/blob/master/app/build.gradle#L40

add 'fr' here

**Comment by xerta555** [comment]
> 
> 
> [https://github.com/LSPosed/LSPosed/blob/master/app/build.gradle#L40](https://github.com/LSPosed/LSPosed/blob/master/app/build.gradle?rgh-link-date=2021-02-27T16%3A26%3A43Z#L40)
> 
> add 'fr' here

Done here: https://github.com/LSPosed/LSPosed/pull/224

**Comment by yujincheng08** [comment]
man, do this in this pr plz.

**Comment by tehcneko** [comment]
> > [https://github.com/LSPosed/LSPosed/blob/master/app/build.gradle#L40](https://github.com/LSPosed/LSPosed/blob/master/app/build.gradle?rgh-link-date=2021-02-27T16%3A26%3A43Z#L40)
> > add 'fr' here
> 
> Done here: #224

in this pr please

**Comment by xerta555** [comment]
> 
> 
> man, do this in this pr plz.

Idk how to do that sorry :/

**Comment by tehcneko** [comment]
edit that file here
https://github.com/xerta555/LSPosed/tree/patch-1

**Comment by xerta555** [comment]
> edit that file here

Done 👍🏻

**Review by yujincheng08 — APPROVED** [review]
lgtm

**Pull request merged**
