### PR TITLE
[app] Update RikkaX core

### PR DESCRIPTION
**Pull request by tehcneko**

### CODE REVIEW

**Review by aviraxp — APPROVED** [review]

**Comment by Pandemic-XDA** [comment]
When will the translations being added from here ?
https://weblate.rikka.app/projects/libraries/
Juat curious 😎😘

**Comment by JasonKhew96** [comment]
> When will the translations being added from here ?
> https://weblate.rikka.app/projects/libraries/
> Just curious 😎😘

added

**Comment by Pandemic-XDA** [comment]
Great 😎💪

**Comment by Pandemic-XDA** [comment]
> > When will the translations being added from here ?
> > https://weblate.rikka.app/projects/libraries/
> > Just curious 😎😘
> 
> added
> 

Still not added 
IMG_20210321_175237_766

**Pull request merged**
