### PR TITLE
Update French translation

### PR DESCRIPTION
**Pull request by xerta555**

### CODE REVIEW

**Review by yujincheng08 — CHANGES_REQUESTED** [review]
u dont hv to translate those strings with translateble=false.

**Comment by xerta555** [comment]
> u dont hv to translate those strings with translateble=false.

Why?
Why is this a problem?

**Comment by yujincheng08** [comment]
because it makes no sense and takes no effect but makes linter unhappy: it throws annoying warnings.

**Comment by xerta555** [comment]
> because it makes no sense and takes no effect but makes linter unhappy: it throws annoying warnings.

So why don't just removing that?

**Comment by yujincheng08** [comment]
because we dont want them to be translated... How comes a URL be translated...

**Comment by xerta555** [comment]
> because we dont want them to be translated... How comes a URL be translated...

So don't keep that in the translations files, just hardcode it..
It doesn't make sense to have untranslatable lines in the translation files.

**Comment by yujincheng08** [comment]
ofcourse it makes sense to have untranslatable strings in xml. They can be  shared between different xml layouts.

**Comment by xerta555** [comment]
> ofcourse it makes sense to have untranslatable strings in xml. They can be shared between different xml layouts.

My God...all this just for this...
I strongly suggest to move these famous translatable lines to another xml file that we, the translators will not need to go and look at.

This is just a suggestion to make the whole translation system easier.

**Comment by yujincheng08** [comment]
pr is welcome.

**Comment by xerta555** [comment]
> pr is welcome.

Why don't move theses lines to a new xml file so?

**Comment by yujincheng08** [comment]
ofcourse its okay. Thats why i said pr is welcome if u wanna do so.

**Comment by xerta555** [comment]
> ofcourse its okay. Thats why i said pr is welcome if u wanna do so.

I can move these 2-3 lines into a new xml file that I will put in the same folder.
But, not being a experienced Github user, i will certainly take more time than you to do this ^^

**Comment by yujincheng08** [comment]
i am afk so...

**Comment by xerta555** [comment]
> i am afk so...

I transmitted, in a very clumsy way, but made.

**Pull request closed without merging**
