### PR TITLE
Update Korean translation

### PR DESCRIPTION
**Pull request by green1052**

### CODE REVIEW

**Review by yujincheng08 — APPROVED** [review]

**Comment by green1052** [comment]
thx!

**Comment by yujincheng08** [comment]
? why are u closing it

**Comment by green1052** [comment]
Can't we close it? I'm sorry.

**Comment by yujincheng08** [comment]
if u close it, we cant merge...

**Comment by green1052** [comment]
https://github.com/LSPosed/LSPosed/pull/258 uploaded again.

**Pull request closed without merging**
