### PR TITLE
Update French translation

### PR DESCRIPTION
**Pull request by xerta555**
Note:
- For "Activated" at line 26, if this string is for the variant enabled on the main screen (first info on the main screen), add variant variable to the default en string file, translator like me could fix it
- The third setting in the settings screen of the app (in English "Dark theme") don't exist in the https://github.com/LSPosed/LSPosed/blob/master/app/src/main/res/values/strings.xml file

### CODE REVIEW

**Comment by yujincheng08** [comment]
Those non-exists strings are from dependencies

**Comment by xerta555** [comment]
> Those non-exists strings are from dependencies
> 
> I think they might be overridden?

The two problems are:
- for the first, in French language (for exemple), the dependency string and the translated string must be inverted
- for the second one, in the case where the French user don't understand English, he willn't understand what's this option and will don't know how to set it.

I had seen that some other strings contains variables, exemple `%2$s`, why don't use the same thing for this string ?

**Comment by yujincheng08** [comment]
1. Those are our faults and we will fix it
2. As said, though they are from the dependencies, they can be overridden so they can also be translated to other languages

**Comment by yujincheng08** [comment]
plz see #237

**Comment by xerta555** [comment]
> 
> 
> plz see #239

Nice 👍🏻

**Comment by yujincheng08** [comment]
Please see if I fixed the conflict correctly, and override those strings that are not in en.

**Comment by xerta555** [comment]
> 
> 
> Please see if I fixed the conflict correctly, and override those strings that are not in en.

If u mean about this https://github.com/LSPosed/LSPosed/pull/236/commits/5d83c0d968abab87a0c423ea9d606be1133a0c15 so yes, it's correct.

**Comment by yujincheng08** [comment]
No I mean 5d83c0d968abab87a0c423ea9d606be1133a0c15

**Review by yujincheng08 — APPROVED** [review]

**Pull request merged**
