### PR TITLE
edited strings.xml

### PR DESCRIPTION
**Pull request by Pandemic-XDA**
added some missings lines

### CODE REVIEW

**Comment by yujincheng08** [comment]
filename is wrong.

**Comment by Pandemic-XDA** [comment]
There stands an double ss before strings.xml by mistake, delete 1 s and should be fine

**Comment by yujincheng08** [comment]
Then do so and reopen this pr.

**Comment by Pandemic-XDA** [comment]
Yeah oke but how, dunno

**Comment by yujincheng08** [comment]
google can help u, instead of I.

**Comment by Pandemic-XDA** [comment]
Its kinda unclear and cant find the answer -__-

**Comment by Pandemic-XDA** [comment]
I edited the previous values-nl strings.xml, can that be added in lsposed Manager ?

**Pull request closed without merging**
