### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by a0533057932**
Hebrew translation update

### CODE REVIEW

**Comment by yujincheng08** [comment]
do this in https://lsposed.crowdin.com/u/projects/1

**Comment by a0533057932** [comment]
I did there
I'm just pretty new to GitaHab
Sorry if I did something wrong



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
16.01.22,
05:08:52

‫בתאריך יום א׳, 16 בינו׳ 2022 ב-5:07 מאת ‪LoveSy‬‏ <‪
***@***.***‬‏>:‬

**Comment by yujincheng08** [comment]
ok, see #1540

**Comment by a0533057932** [comment]
Thank you



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
16.01.22,
05:16:21

‫בתאריך יום א׳, 16 בינו׳ 2022 ב-5:14 מאת ‪LoveSy‬‏ <‪
***@***.***‬‏>:‬

**Pull request closed without merging**
